# Generated by Django 6.0.5 on 2026-08-22 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_room_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
